project:
  type: website
  output-dir: docs/
  render: 
    - index.qmd
    - AB_*
website:
  google-analytics: 
    tracking-id: "G-B7X33YDF5P"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Welcome to the Alpha Beta Dashboard"
    type: info
    position: below-navbar  
  title: "Alpha Beta T cells"
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    - text: "Frequency"
      menu:
      - text: "CD4"
        href: AB_CD4.qmd
      - text: "CD8"
        href: AB_CD8.qmd
      - text: "DN"
        href: AB_DN.qmd
      - text: "Vd2"
        href: AB_Vd2.qmd
      - text: "Va7.2"
        href: AB_Va7.qmd
      - text: "T cells"
        href: AB_Tcells.qmd
      - text: "B cells"
        href: AB_Bcells.qmd
      - text: "Monocytes"
        href: AB_Monocytes.qmd
    - text: "Counts"
      menu:
      - text: "CD45"
        href: AB_CD45Count.qmd
      - text: "T cells"
        href: AB_TcellsCount.qmd
    right:
    - text: "Help"
      href: index.qmd
    - text: "Download Data"
      href: index.qmd
    - text: "Other"
      menu:
      - text: "Miscellaneous"
        href: index.qmd
    - icon: github
      href: https://github.com/DavidRach/AlphaBeta
      aria-label: GitHub
  page-footer:
    background: light
    left: University of Maryland, Baltimore
    right: Built with [Quarto](https://quarto.org/).

format:
  html:
    theme: styles.scss