---
title: "T cells Count"
toc: true
---


```{r}
#| include: FALSE
#| message: FALSE
#| warning: FALSE
library(dplyr)
library(ggplot2)
library(Coereba)

Variable <- "Tcells_count"
```

```{r}
#| include: FALSE
shape_sex <- c("Female" = 22, "Male" = 21)
fill_sex <- c("Female" = "white", "Male" = "black")

shape_ptype <- c("HU" = 22, "HEU-lo" = 21, "HEU-hi" = 21)
fill_ptype <- c("HU" = "white", "HEU-lo" = "darkgray", "HEU-hi" = "black")

shape_art <- c("HU" = 22, "HEU" = 21)
fill_art <- c("HU" = "white", "HEU" = "black")

shape_viral <- c("NoViral" = 22, "Viral" = 21)
fill_viral <- c("NoViral" = "white", "Viral" = "black")
```


```{r}
#| include: FALSE
Data <- read.csv("data/openCytoRatios.csv", check.names=FALSE)
Data$ptype <- factor(Data$ptype, levels = c("HU", "HEU-lo", "HEU-hi"))
Data$timepoint <- factor(Data$timepoint, levels = c(0, 4, 9))

CtrlData <- Data |> filter(Condition %in% "Ctrl")

PPDData <- Data |> filter(Condition %in% "PPD")

SEBData <- Data |> filter(Condition %in% "SEB")
```

# Control 

```{r}
#| warning: FALSE
#| include: FALSE

ControlPlot <- Utility_LongitudinalBehemoth(data=CtrlData, Variable=Variable,
 GlobalFactor="timepoint", LocalFactor="ptype", shape_palette = shape_ptype,
 fill_palette = fill_ptype)

ControlPlot  <- ControlPlot + labs(y="T cells per sample")
```

```{r}
#| echo: FALSE
#| warning: FALSE

ControlPlot
```

# PPD
```{r}
#| warning: FALSE
#| include: FALSE

PPDPlot <- Utility_LongitudinalBehemoth(data=PPDData, Variable=Variable,
 GlobalFactor="timepoint", LocalFactor="ptype", shape_palette = shape_ptype,
 fill_palette = fill_ptype)

PPDPlot <- PPDPlot + labs(y="T cells per sample")
```

```{r}
#| echo: FALSE
#| warning: FALSE

PPDPlot
```

# SEB
```{r}
#| warning: FALSE
#| include: FALSE

SEBPlot <- Utility_LongitudinalBehemoth(data=SEBData, Variable=Variable,
 GlobalFactor="timepoint", LocalFactor="ptype", shape_palette = shape_ptype,
 fill_palette = fill_ptype)

SEBPlot <- SEBPlot + labs(y="T cells per sample")
```

```{r}
#| echo: FALSE
#| warning: FALSE
SEBPlot
```


